name: Notion API test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: print log
        run: echo "こんにちは"
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - name: Fetch Notion API
        run: |
          echo $NOTION_DATABASE_ID
          echo $NOTION_KEY
      - name: Fetch Notion API
        run: |
          curl -X POST https://api.notion.com/v1/databases/$NOTION_DATABASE_ID/query -H "Authorization: Bearer $NOTION_KEY" -H "Content-Type: application/json" -H "Notion-Version: 2022-06-28" | jq .
